# Generated by Django 4.0.6 on 2022-07-26 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='機種名')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '機器',
                'verbose_name_plural': '機器',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='サービス名')),
                ('sort_no', models.IntegerField(verbose_name='表示順')),
            ],
            options={
                'verbose_name': 'サービス',
                'verbose_name_plural': 'サービス',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '状態',
                'verbose_name_plural': '状態',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sort_no', models.IntegerField(verbose_name='表示順')),
            ],
            options={
                'verbose_name': '種別',
                'verbose_name_plural': '種別',
            },
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30, verbose_name='コープ名')),
                ('serial', models.CharField(max_length=50, verbose_name='機器ID')),
                ('arrival', models.DateField(verbose_name='入荷日')),
                ('delivery', models.DateTimeField(blank=True, null=True, verbose_name='持出日')),
                ('use', models.DateField(blank=True, null=True, verbose_name='使用日')),
                ('customer', models.CharField(blank=True, max_length=30, verbose_name='顧客')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('log', models.TextField(blank=True, verbose_name='ログ')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.device', verbose_name='機種名')),
            ],
            options={
                'verbose_name': '在庫リストベース',
                'verbose_name_plural': '在庫リストベース',
            },
        ),
    ]
