# Generated by Django 4.0.6 on 2022-07-26 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('stocks', '0003_alter_stockdata_options_stockdata_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='job',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.job', verbose_name='業種'),
        ),
    ]
