# Generated by Django 4.0.6 on 2022-09-16 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('stocks', '0004_alter_stockdata_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='delivery',
            field=models.DateField(blank=True, null=True, verbose_name='持出日'),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.job', verbose_name='業種'),
        ),
    ]
